name: sendlyme
description: SendlyMe P2P File Transfer

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  barcode_scan: ^0.0.4
  qr_flutter: ^2.0.0
  file_picker: ^1.0.3
  http: ^0.12.0
  json_serializable: ^2.0.1
  path_provider: ^0.5.0
  screen: ^0.0.4
  shared_preferences: ^0.5.1+1
  modal_progress_hud: ^0.1.3
  open_file: ^2.0.1+2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^4.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: PTSerif
      fonts:
          - asset: fonts/PT_Serif-Web-Italic.ttf
            style: italic
          - asset: fonts/PT_Serif-Web-Regular.ttf
            style: normal
    - family: IceBerg
      fonts:
          - asset: fonts/Iceberg-Regular.ttf
  assets:
    - join.png
    - start.png
    - send_logo.gif
    - splash.gif
    - start_background.png
    - qr.ico
    - join.ico
    - assets/i18n/tr.json
    - assets/i18n/en.json
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
